trigger:
- main  # Trigger the pipeline on commits to the 'main' branch

pool:
  vmImage: 'ubuntu-latest' # Use a Microsoft-hosted Ubuntu agent

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml' # Path to your pom.xml file
    goals: 'clean package' # Maven goals to execute (clean and package)
    publishJUnitResults: true # Publish JUnit test results (if any)
    testResultsFiles: '**/surefire-reports/TEST-*.xml' # Pattern for test result files
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8' # Or your desired Java version
    mavenVersionOption: '3.6.x' # Or your desired Maven version
