trigger:
  branches:
    include:
      - main  # Trigger the pipeline on changes to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # The environment for running the pipeline (Ubuntu VM in this case)

steps:
  - task: UseNode@2  # Use Node.js task to specify Node.js version
    inputs:
      versionSpec: '16.x'
      addToPath: true

  - script: |
      npm install  # Install the dependencies
      npm test      # Run tests
    displayName: 'Install dependencies and run tests'

  - task: PublishBuildArtifacts@1  # Publish artifacts task (optional, but useful for storing build outputs)
    inputs:
      artifactName: 'drop'
      publishLocation: 'Container'
