trigger:
  branches:
    include:
      - main  # Trigger the pipeline on changes to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu VM image for the build environment

steps:
  # Step 1: Checkout the code from the repository
  - task: Checkout@1

  # Step 2: Set up Maven environment
  - task: UseMaven@3  # Use the Maven task to set up Maven

    inputs:
      mavenVersionOption: 'Default'  # You can specify a custom version if needed

  # Step 3: Build the project using Maven
  - script: mvn clean install  # Clean the project and run the Maven build
    displayName: 'Build with Maven'

  # Step 4: Run tests with Maven (optional, if your project includes tests)
  - script: mvn test  # Run tests using Maven
    displayName: 'Run Tests'

  # Step 5: Publish build artifacts (optional)
  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'drop'  # Name for the build artifact
      publishLocation: 'Container'  # Artifact storage location (you can choose 'FileShare' or 'Container')
