trigger:
  branches:
    include:
      - main  # Trigger on the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image

steps:
  - task: UseNode@1  # Use Node.js task version 1
    inputs:
      versionSpec: '16.x'  # Specify the Node.js version
      addToPath: true  # Add Node.js to the system PATH

  - script: |
      npm install  # Install dependencies
      npm test      # Run tests
    displayName: 'Install dependencies and run tests'
